.DEFAULT_GOAL := build

.PHONY: fmt vet build build-only clean test test-verbose

fmt:
	go fmt ./...

vet:
	go vet ./...

build-only:
	go build ./...

build: vet build-only

clean:
	go clean
	go clean -testcache

test: build
	go clean -testcache && go test -cover ./...

test-verbose: build
	go clean -testcache && go test -v -cover ./...
