apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init
  labels:
    {{- include "chart.labels" . | nindent 4 }}
data:
  init.sql: |
    -- Create the telemetry user
    SELECT 'CREATE USER telemetry'
    WHERE NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = 'telemetry')\gexec

    -- Create staging database and grant telemetry user access
    SELECT 'CREATE DATABASE staging WITH TEMPLATE template0'
    WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'staging')\gexec
    GRANT ALL PRIVILEGES ON DATABASE staging TO telemetry;

    -- Create operational database and grant telemetry user access
    SELECT 'CREATE DATABASE operational WITH TEMPLATE template0'
    WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname= 'operational')\gexec
    GRANT ALL PRIVILEGES ON DATABASE operational TO telemetry;

    -- Create telemetry database and grant telemetry user access
    SELECT 'CREATE DATABASE telemetry WITH TEMPLATE template0'
    WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname= 'telemetry')\gexec
    GRANT ALL PRIVILEGES ON DATABASE telemetry TO telemetry;
