apiVersion: batch/v1
kind: CronJob
metadata:
  name: postgres-backup
  namespace: {{ .Release.Namespace }}
spec:
  schedule: {{ required "A value for schedule is required" .Values.postgres.backup.schedule | quote }}
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: {{ .Values.postgres.backup.containerName }}
              image: {{ .Values.postgres.backup.containerImage }}
              command:
                - sh
                - -c
                - |
                  apt update
                  apt install -y awscli
                  pg_dump -h postgres -U $POSTGRES_USER $POSTGRES_DB > /backup/backup.sql
                  aws s3 cp /backup/backup.sql s3://$AWS_BUCKET/backups/backup-$(date +%Y%m%d).sql
              env:
                - name: POSTGRES_USER
                  valueFrom:
                    secretKeyRef:
                      name: postgres-config
                      key: POSTGRES_USER
                - name: PGPASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: postgres-config
                      key: POSTGRES_PASSWORD
                - name: POSTGRES_DB
                  valueFrom:
                    secretKeyRef:
                      name: postgres-config
                      key: POSTGRES_DB
                - name: AWS_ACCESS_KEY_ID
                  valueFrom:
                    secretKeyRef:
                      name: aws-credentials
                      key: aws_access_key_id
                - name: AWS_SECRET_ACCESS_KEY
                  valueFrom:
                    secretKeyRef:
                      name: aws-credentials
                      key: aws_secret_access_key
                - name: AWS_BUCKET
                  value: {{ .Values.postgres.backup.awsBucket }}
              volumeMounts:
                - name: backup-storage
                  mountPath: /backup
          volumes:
            - name: backup-storage
              emptyDir: {}
