apiVersion: batch/v1
kind: Job
metadata:
  name: postgres-init
  namespace: telemetry
spec:
  template:
    spec:
      containers:
        - name: init-db
          image: postgres:16
          command:
            - sh
            - -c
            - |
              until pg_isready -h postgres -U postgres; do sleep 1; done
              psql -h postgres -U postgres -f /scripts/init.sql
          env:
            - name: PGPASSWORD
              value: telemetry
          volumeMounts:
            - name: init-sql
              mountPath: /scripts/init.sql
              subPath: init.sql
      restartPolicy: OnFailure
      volumes:
        - name: init-sql
          configMap:
            name: postgres-init
