apiVersion: batch/v1
kind: Job
metadata:
  name: postgres-init
  namespace: {{ .Release.Namespace }}
spec:
  template:
    spec:
      containers:
        - name: init-db
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          command:
            - sh
            - -c
            - |
              until pg_isready -h postgres -U $POSTGRES_USER; do sleep 1; done
              psql -h postgres -U $POSTGRES_USER -f /scripts/init.sql
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-config
                  key: POSTGRES_USER
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-config
                  key: POSTGRES_PASSWORD
          volumeMounts:
            - name: init-sql
              mountPath: /scripts/init.sql
              subPath: init.sql
      restartPolicy: OnFailure
      volumes:
        - name: init-sql
          configMap:
            name: postgres-init
