apiVersion: v1
kind: Secret
metadata:
  name: postgres-config
  labels:
    {{- include "chart.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  POSTGRES_DB: {{ .Values.postgres.db | b64enc }}
  POSTGRES_USER: {{ .Values.postgres.user | b64enc }}
  POSTGRES_PASSWORD: {{ .Values.postgres.password | b64enc }}
