apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TCPRoute
metadata:
  name: postgres-route
  namespace: istio-system
spec:
  parentRefs:
    - name: itpe-istio-gateway
      namespace: istio-system
  rules:
  - matches:
      - hostname: "postgres.local"
        port: 5432
  - backendRefs:
    - name: postgres
      port: 5432
