services:
  tsg:
    image: telemetry/server
    build:
      context: telemetry-server
      args:
        cfgFile: composeServer.yaml
    expose:
      - 9999
    networks:
      - external
    ports:
      - "9999:9999"
    healthcheck:
      test: ["CMD-SHELL", "curl --fail --insecure http://tsg:9999/healthz || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 10

volumes:
  pgdata:

networks:
  external: {}
