services:
  tsg:
    image: telemetry/server
    build:
      context: ..
      target: telemetry-server
      args:
        serverCfg: composeServer.yaml
    expose:
      - 9999
    networks:
      - external
      - internal
    ports:
      - "9999:9999"
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl --fail --insecure http://tsg:9999/healthz || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 40

  tsa:
    image: telemetry/admin
    build:
      context: ..
      target: telemetry-admin
      args:
        adminCfg: composeAdmin.yaml
    expose:
      - 9998
    networks:
      - external
      - internal
    ports:
      - "9998:9998"
    depends_on:
      tsg:
        condition: service_healthy
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl --fail --insecure http://tsa:9998/healthz || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 40

  db:
    image: telemetry/postgres
    build:
      context: postgres
    restart: always
    networks:
      - internal
    environment:
      POSTGRES_PASSWORD: telemetry
      POSTGRES_USER: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 1s
      timeout: 5s
      retries: 10
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:

networks:
  external: {}
  internal: {}
