apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "chart.fullname" . }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
  annotations: {}
spec:
  backoffLimit: 6
  template:
    metadata:
      labels:
        {{- include "chart.labels" . | nindent 8 }}
      annotations:
        checksum/init-sql: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      restartPolicy: OnFailure
      serviceAccountName: {{ include "chart.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: database-init
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          command: ["/bin/bash", "/telemetry/initdb.bash"]
          env:
            - name: TELEMETRY_POSTGRES
              value: {{ .Values.postgres.host | quote }}
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: telemetry-postgres-config
                  key: POSTGRES_USER
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: telemetry-postgres-config
                  key: POSTGRES_PASSWORD
            - name: BI_TEAM_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database-init-config
                  key: BI_TEAM_USER_PASS
            - name: TELEMETRY_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database-init-config
                  key: TELEMETRY_USER_PASS
          volumeMounts:
            - name: init-sql-template
              mountPath: /telemetry/init.sql.template
              subPath: init.sql.template
            - name: initdb-bash
              mountPath: /telemetry/initdb.bash
              subPath: initdb.bash
            - name: writable-dir
              mountPath: /tmp/telemetry
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: init-sql-template
          configMap:
            name: database-init-scripts
        - name: initdb-bash
          configMap:
            name: database-init-scripts
        - name: writable-dir
          emptyDir: {}
