apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tls-telemetry-ingress
spec:
  {{- $fqdn := include "telemetry.fqdn" . }}
  secretName: tls-telemetry-ingress
  duration: 720h # 30 days. The max duration is set by the CA at 30 days.
  renewBefore: 168h # 7d
  subject:
    organizations:
      - {{ $fqdn | quote }}
  commonName: {{ $fqdn | quote }}
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - server auth
  dnsNames:
    - {{ $fqdn | quote }}
  issuerRef:
    name: suse-internal-ca
    kind: ClusterIssuer
    group: cert-manager.io