apiVersion: v1
kind: ConfigMap
metadata:
  name: telemetry-server-config
  labels:
    {{- include "chart.labels" . | nindent 4 }}
data:
  pre-init-checks: |
    {{- .Files.Get "scripts/pre-init-checks.sh" | nindent 4 }}
  file-from-cfgmap: |
    {{- toYaml .Values.config | nindent 4 }}
