apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: postgres-credentials
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook-weight": "-5"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: SecretStore
  target:
    name: telemetry-postgres-config
    creationPolicy: Owner
  data:
    - secretKey: POSTGRES_USER
      remoteRef:
        key: {{ .Values.awscredentials.secretName }}
        property: username
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: {{ .Values.awscredentials.secretName }}
        property: password
