{{- if not .Values.external.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: telemetry-postgres-config
  labels:
    {{- include "chart.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  POSTGRES_USER: {{ .Values.postgres.user | b64enc }}
  POSTGRES_PASSWORD: {{ .Values.postgres.password | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials
  labels:
    {{- include "chart.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  aws_access_key_id: {{ .Values.awscredentials.accessKeyId | b64enc }}
  aws_secret_access_key: {{ .Values.awscredentials.secretAccessKey | b64enc }}
{{- end -}}
