apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: aws-secretsmanager
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook-weight": "-10"
spec:
  provider:
    aws:
      service: SecretsManager
      region: {{ .Values.awscredentials.region }}
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: aws-credentials
            key: aws_access_key_id
          secretAccessKeySecretRef:
            name: aws-credentials
            key: aws_secret_access_key
