apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.serviceName }}
  namespace: {{ .Release.Namespace }}
spec:
  type: ExternalName
  {{- $pgHost := printf "%s.%s.%s" (include "chart.fullname" .) .Release.Namespace "svc.cluster.local" }}
  {{- if .Values.external.enabled }}
  {{- $pgHost = .Values.external.hostname }}
  {{- end }}
  externalName: {{ $pgHost }}
