{{- if not .Values.external.enabled -}}
{{- if not .Values.storage.openplatform.enabled -}}
kind: PersistentVolume
apiVersion: v1
metadata:
  name: telemetry-postgres-db-pv
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  {{- $pvc := .Values.storage.local.pvc }}
  storageClassName: {{ $pvc.storageClass | quote }}
  capacity:
    storage: {{ $pvc.storageSize | quote }}
  accessModes:
    - {{ $pvc.accessMode | quote }}
  hostPath:
    path: "/mnt/data"
{{- end -}}
{{- end -}}
