replicaCount: 1

# A valid image tag must be provided for the desired postgres version
image:
  repository: postgres
  pullPolicy: IfNotPresent
  tag: "16"

podAnnotations: {}
podLabels: {}

service:
  port: 5432
  type: ClusterIP

resources:
  limits:
    cpu: 500m
    memory: 256Mi
  requests:
    cpu: 500m
    memory: 256Mi

volumes:
- name: postgres-volume
  persistentVolumeClaim:
    claimName: postgres-pv-claim

volumeMounts:
- mountPath: /var/lib/postgresql/data
  name: postgres-volume
  subPath: data

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80

# TODO: this must be passed in as envs within CI/CD
postgres:
  db: operational
  user: postgres
  password: telemetry
  backup:
    containerImage: postgres:16
    containerName: postgres-backup
    awsBucket: test-ts-postgres-backup
    # For testing purposes, scheduled to backup every minute, change as needed
    schedule: "* * * * *"

awscredentials:
  accessKeyId: foo
  secretAccessKey: bar

# OpenPlatform deployment
# Defaults to enabled: true. Switch to false for local development
openplatform:
  enabled: true
  pvc:
    storageClass: ebs
    accessMode: ReadWriteOnce
    storageSize: 5Gi
  backupSchedule: "0 0 * * 0-6"
