apiVersion: v1
kind: ConfigMap
metadata:
  name: rds-postgres-init
  labels:
    {{- include "chart.labels" . | nindent 4 }}
data:
  init.sql: |
    {{- .Files.Get "docker/postgres/telemetry/init.sql.template" | nindent 4 }}
