apiVersion: v1
kind: ConfigMap
metadata:
  name: rds-postgres-init
  labels:
    {{- include "chart.labels" . | nindent 4 }}
data:
  init.sql.template: |
    {{- .Files.Get "scripts/init.sql.template" | nindent 4 }}
  initdb.bash: |
    {{- .Files.Get "scripts/initdb.bash" | nindent 4 }}
