apiVersion: v1
kind: ConfigMap
metadata:
  name: rds-postgres-init
  labels:
    {{- include "chart.labels" . | nindent 4 }}
data:
  init.sql: |
    {{- .Files.Get "scripts/create-users.sql" | nindent 4 }}
