---

name: Run Pull Request CI Verification

on:
  pull_request:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest
    container:
      image: registry.suse.com/bci/golang:1.21-openssl

    steps:
      - name: Checkout PR sources
        uses: actions/checkout@v4
        with:
          path: telemetry-server

      - name: Checkout SUSE/telemetry companion sources
        uses: actions/checkout@v4
        with:
          repository: SUSE/telemetry
          path: telemetry

      - name: Run tests in verbose mode
        run: cd telemetry-server && make test-verbose
